stages:
  - build
  - deploy

services:
  - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

Build container image:
  stage: build
  image: docker:stable
  before_script:
    - sleep 5
    - docker version
  script:
    - docker build --no-cache -t "mcronce/lunchbox:$CI_COMMIT_SHORT_SHA" . || sleep 3600
  after_script:
    - docker rmi -f "mcronce/lunchbox:$CI_COMMIT_SHORT_SHA"

Push container image:
  stage: deploy
  image: docker:stable
  script:
    - docker build --no-cache -t "mcronce/lunchbox:${CI_COMMIT_TAG:-latest}" .
    - docker push "mcronce/lunchbox:${CI_COMMIT_TAG:-latest}"
  after_script:
    - docker rmi -f "mcronce/lunchbox:${CI_COMMIT_TAG:-latest}"

