stages:
  - test
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://127.0.0.1:2375

Test Rust code:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test

Build container image:
  stage: build
  image: docker:stable
  script:
    - docker build --no-cache -t "mcronce/lunchbox:$CI_COMMIT_SHORT_SHA" . || sleep 3600
  after_script:
    - docker rmi -f "mcronce/lunchbox:$CI_COMMIT_SHORT_SHA"

Push container image:
  stage: deploy
  image: docker:stable
  script:
    - docker build --no-cache -t "mcronce/lunchbox:${CI_COMMIT_TAG:-latest}" .
    - docker push "mcronce/lunchbox:${CI_COMMIT_TAG:-latest}"
  after_script:
    - docker rmi -f "mcronce/lunchbox:${CI_COMMIT_TAG:-latest}"

