[package]
name = "lunchbox-macros"
version = "0.1.0"
authors = ["Mike Cronce <mike@cronce.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "~1"
quote = "~1"
syn = {version = "~1", features = ["full"]}

